# For more information read: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions

name: TOT CICD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/webapp-release:v1

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        working-directory: app
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t "$IMAGE" .

      - name: Push image
        run: docker push "$IMAGE"